# Generated by Django 3.2.13 on 2023-12-20 18:42

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=150, verbose_name='Name of shop')),
                ('description', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(500)], verbose_name='Description of shop')),
                ('type_of_shop', models.CharField(choices=[('SPORT', 'Sport'), ('FOOD', 'Food'), ('ELECTRONIC', 'Electronic')], max_length=10, verbose_name='Shop type')),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0, max_digits=2, verbose_name='Sales commission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
